# <핵심만 요약한 데이터 조작과 시각화 파이썬 코드북>
**각 코드를 설명하는 주석과 연습문제 풀이는 도서에서 확인**할 수 있습니다. 성공적인 학습을 응원합니다.
- ⓒ2024 AlgoBoni all rights reserved.
- 본 컨텐츠의 저작권은 알고보니에 있습니다. 저작권법에 의해 보호를 받는 저작물이므로 무단 전재와 무단 복제를 금합니다.
- 본 컨텐츠의 종이책은 [교보문고](https://product.kyobobook.co.kr/detail/S000213616715), [예스24](https://www.yes24.com/Product/Goods/128117125), [알라딘](https://www.aladin.co.kr/shop/wproduct.aspx?ItemId=341725290)에서 구매할 수 있습니다.

## 3장. 배열

### 3-1. 배열 만들기: array, zeros, ones, arange, randint

In [23]:
import numpy as np
array1 = np.array([1,2,3,4,5])
print(array1)
print(">>> type: ", type(array1))

[1 2 3 4 5]
>>> type:  <class 'numpy.ndarray'>


In [24]:
array2 = np.zeros(5) 
print(array2)

array3 = np.ones((2,3)) 
print(array3)

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]


In [25]:
array4 = np.arange(-2,9,1) 
print(array4)

array5 = np.arange(-2,9,2) 
print(array5)

[-2 -1  0  1  2  3  4  5  6  7  8]
[-2  0  2  4  6  8]


In [26]:
array6 = np.random.randint(-100,100,5) 
print(array6)

[ 34  65 -10 -32 -52]


### 3-2. 배열 저장하기 및 불러오기: save, load

In [27]:
np.save('array6.npy', array6)
loaded = np.load('array6.npy')
print(loaded)

[ 34  65 -10 -32 -52]


### 3-3. 배열 요소 추출하기
### - 인덱싱과 슬라이싱

In [28]:
num_array = np.arange(10, 110, 10)
print(num_array, "\n")

print(num_array[0])
print(num_array[-1])
print(num_array[1:6])
print(num_array[1:6:2])
print(num_array[1::2])
print(num_array[6:])

[ 10  20  30  40  50  60  70  80  90 100] 

10
100
[20 30 40 50 60]
[20 40 60]
[ 20  40  60  80 100]
[ 70  80  90 100]


### - 최솟값 및 최댓값의 인덱스 추출: argmin, argmax

In [30]:
num_array = np.arange(10, 110, 10)
print(num_array)

MIN, MAX = np.argmin(num_array), np.argmax(num_array)
print(MIN, MAX)

[ 10  20  30  40  50  60  70  80  90 100]
0 9


### - 조건을 만족하는 요소의 인덱스 추출: where, any, all

In [36]:
num_array = np.arange(10, 110, 10)
print(num_array)

idx1 = np.where(num_array >= 50) 
print(idx1) 

print(num_array[idx1])

[ 10  20  30  40  50  60  70  80  90 100]
(array([4, 5, 6, 7, 8, 9]),)
[ 50  60  70  80  90 100]


In [37]:
result1 = np.where(num_array!=50, num_array*0.01, 5) 
print(result1)

[0.1 0.2 0.3 0.4 5.  0.6 0.7 0.8 0.9 1. ]


In [38]:
print(np.any(num_array > 80))
print(np.all(num_array > 80))

True
False


### 3-4. 배열 편집하기

### - 추가하기: append, insert

In [61]:
import numpy as np
numbers = np.array([10, 20, 30, 40, 50])

numbers1 = np.append(numbers, 60) 
print(numbers1)

numbers2 = np.append(numbers, [70, 80]) 
print(numbers2)

numbers3 = np.insert(numbers, 0, 1) 
print(numbers3)

[10 20 30 40 50 60]
[10 20 30 40 50 70 80]
[ 1 10 20 30 40 50]


In [65]:
numbers = np.array([10, 20, 30, 40, 50])
numbers_str = np.append(numbers, 'a')
print(numbers_str) 

numbers_float = np.append(numbers, 0.1)
print(numbers_float)

['10' '20' '30' '40' '50' 'a']
[10.  20.  30.  40.  50.   0.1]


### - 수정하기: 인덱싱과 슬라이싱

In [72]:
numbers = np.array([10, 20, 30, 40, 50])

numbers[0] = 1
print(numbers)

numbers[-1] = 5 
print(numbers)

numbers[3:] = 0
print(numbers)

[ 1 20 30 40 50]
[ 1 20 30 40  5]
[ 1 20 30  0  0]


### - 삭제하기: delete, unique

In [79]:
numbers = np.array([10, 20, 30, 40, 50])
print(numbers)

del_numbers = np.delete(numbers, 0) 
print(del_numbers)

[10 20 30 40 50]
[20 30 40 50]


In [85]:
array2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array2d, "\n")

del_array2d1 = np.delete(array2d, 0, axis=0) 
print(del_array2d1, "\n")

del_array2d2 = np.delete(array2d, 0, axis=1) 
print(del_array2d2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]
 [8 9]]


In [86]:
numbers = np.array([1,1,1,2,3,4,5,5,6])
print(numbers)
print(np.unique(numbers), '\n')

result, count = np.unique(numbers, return_counts=True)
print(result) 
print(count)

[1 1 1 2 3 4 5 5 6]
[1 2 3 4 5 6] 

[1 2 3 4 5 6]
[3 1 1 1 2 1]


### 3-5. 배열 재구조화: shape, reshape, T(transpose)

In [45]:
import numpy as np
numbers = np.array([10, 20, 30, 40, 50, 60])
array2d = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
print("numbers.shape ", numbers.shape) 
print("array2d.shape ", array2d.shape) 

numbers.shape  (6,)
array2d.shape  (2, 6)


In [37]:
reshape_numbers1 = numbers.reshape(2, 3) 
print(reshape_numbers1, '\n')
reshape_numbers2 = numbers.reshape(1, -1) 
print(reshape_numbers2, '\n')
reshape_numbers3 = reshape_numbers1.ravel() 
print(reshape_numbers3)

[[10 20 30]
 [40 50 60]] 

[[10 20 30 40 50 60]] 

[10 20 30 40 50 60]


In [47]:
array2d = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])
reshape_array2d1 = array2d.reshape(4, -1) 
print(reshape_array2d1, '\n')

reshape_array2d2 = array2d.reshape(4, 3)
print(reshape_array2d2, '\n')

reshape_array2d3 = array2d.reshape(-1, 2, 2) 
print(reshape_array2d3, '\n')

reshape_array2d4 = array2d.reshape(3, 2, 2) 
print(reshape_array2d4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [48]:
print(array2d, '\n')
print(array2d.T)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[[ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]
 [ 6 12]]


### 3-6. 배열 연결하기: concatenate, c_, r_, hstack, vstack

In [86]:
array2d1 = np.array([[1, 2], [3, 6]]) 
array2d2 = np.array([[3, 9]])
print(array2d1, '\n')
print(array2d2, '\n')
print(array2d2.T)

[[1 2]
 [3 6]] 

[[3 9]] 

[[3]
 [9]]


In [87]:
print(array2d1.shape, array2d2.shape)
combined1 = np.concatenate((array2d1, array2d2), axis=0) 
print(combined1)

(2, 2) (1, 2)
[[1 2]
 [3 6]
 [3 9]]


In [88]:
print(array2d1.shape, array2d2.T.shape)
combined2 = np.concatenate((array2d1, array2d2.T), axis=1)
print(combined2)

(2, 2) (2, 1)
[[1 2 3]
 [3 6 9]]


In [91]:
c_ = np.c_[array2d1, array2d2.T]
r_ = np.r_[array2d1, array2d2]
print("c_\n", c_)
print("r_\n", r_)

c_
 [[1 2 3]
 [3 6 9]]
r_
 [[1 2]
 [3 6]
 [3 9]]


In [92]:
hstack = np.hstack((array2d1, array2d2.T)) 
vstack = np.vstack((array2d1, array2d2))
print("hstack_\n", hstack)
print("vstack_\n", vstack)

hstack_
 [[1 2 3]
 [3 6 9]]
vstack_
 [[1 2]
 [3 6]
 [3 9]]


### 3-7. 배열과 유용한 함수들
### - 통계: sum, mean, min, max, std, var, median, percentile, cumsum, cumprod

In [93]:
numbers = np.arange(1,10)
print(numbers)

print('합', np.sum(numbers))
print('평균', np.mean(numbers))
print('최솟값', np.min(numbers))
print('최댓값', np.max(numbers))
print('표준편차', np.std(numbers))
print('분산', np.var(numbers))
print('중앙값', np.median(numbers))
print('백분위수', np.percentile(numbers, 75))
print('누적합', np.cumsum(numbers))
print('누적곱', np.cumprod(numbers))

[1 2 3 4 5 6 7 8 9]
합 45
평균 5.0
최솟값 1
최댓값 9
표준편차 2.581988897471611
분산 6.666666666666667
중앙값 5.0
백분위수 7.0
누적합 [ 1  3  6 10 15 21 28 36 45]
누적곱 [     1      2      6     24    120    720   5040  40320 362880]


### - 절댓값, 제곱, 제곱근: abs, power, sqrt

In [95]:
numbers = np.arange(-10, 11, 3)
print(numbers)

print("절댓값", np.abs(numbers))
print("제곱", numbers**2, np.power(numbers, 2))
print("(양의)제곱근", (numbers**2)**(1/2), np.sqrt(numbers**2))

[-10  -7  -4  -1   2   5   8]
절댓값 [10  7  4  1  2  5  8]
제곱 [100  49  16   1   4  25  64] [100  49  16   1   4  25  64]
(양의)제곱근 [10.  7.  4.  1.  2.  5.  8.] [10.  7.  4.  1.  2.  5.  8.]


### - 반올림, 올림, 버림: round, ceil, floor

In [96]:
numbers = np.arange(-1, 3, 0.55)
print(numbers)

print('반올림', np.round(numbers, 1)) 
print('올림', np.ceil(numbers)) 
print('버림', np.floor(numbers))

[-1.   -0.45  0.1   0.65  1.2   1.75  2.3   2.85]
반올림 [-1.  -0.4  0.1  0.7  1.2  1.8  2.3  2.9]
올림 [-1. -0.  1.  1.  2.  2.  3.  3.]
버림 [-1. -1.  0.  0.  1.  1.  2.  2.]


### - 지수와 로그: exp, log, log10

In [98]:
numbers = np.array([10, 100, 1000, 10000])
print(numbers)

print("자연로그", np.log(numbers))
print("지수(지수표기법)", np.exp(np.log(numbers))) 

np.set_printoptions(suppress=True) 
print("지수(정수출력)", np.exp(np.log(numbers)))
print("상용로그", np.log10(numbers))

[   10   100  1000 10000]
자연로그 [2.30258509 4.60517019 6.90775528 9.21034037]
지수(지수표기법) [1.e+01 1.e+02 1.e+03 1.e+04]
지수(정수출력) [   10.   100.  1000. 10000.]
상용로그 [1. 2. 3. 4.]


### - 스칼라곱, 배열의 요소별 곱, 행렬곱

In [100]:
array33 = np.arange(1,10).reshape(3,3) 
array31 = np.arange(1,4).reshape(-1,1) 
print(array33)
print(array31, "\n")

print(">>> array33 x 10")
result1 = array33 * 10
print(result1, "\n")

print(">>> array33 x array31")
result2 = array33 * array31 
print(result2, '\n')

print(">>> array33 dot array31")
result3 = np.dot(array33, array31) 
print(result3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]] 

>>> array33 x 10
[[10 20 30]
 [40 50 60]
 [70 80 90]] 

>>> array33 x array31
[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]] 

>>> array33 dot array31
[[14]
 [32]
 [50]]


## 연습문제

### 1. 1 이상 100 미만의 정수 중 랜덤으로 추출한 50개의 요소를 포함하는 1차원 배열 array1을 생성하고 출력하시오. (단, 랜덤 시드는 0으로 고정한다)

### 2. 앞서 생성한 배열 array1의 형태를 5행 10열로 재구조화한 배열 array2를 생성하고 출력하시오.

### 3. array1의 최댓값과 그 인덱스, 최솟값과 그 인덱스를 출력하시오.

### 4. 1 이상 5 이하의 연속된 정수 전체를 요소로 갖는 5행 1열의 배열 array3을 생성하고 출력하시오.

### 5. array2에 array3을 열 방향으로 연결한 array4를 생성하고 출력하시오.

### 6. array4에서 값이 20 미만인 요소들의 값과 인덱스와 총 개수를 출력하시오.

### 7. array4에서 값이 20 미만인 요소들을 1로 변경한 array5를 생성하여 출력하시오.

### 8. array5에 로그를 취하고 소수점 첫째자리까지 반올림한 배열 array6를 생성하여 출력하시오.

### 9. array6의 평균, 표준편차, 1사분위수, 3사분위수를 출력하시오.

### 10. array6의 중복된 값을 제거한 배열 array7을 생성하고, array7의 평균, 표준편차, 1사분위수, 3사분위수를 출력하시오.